routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('login', 'AuthController@index');
Route::get('/login', 'AuthController@index')->name('login');

Route::post('/post-login', 'AuthController@postLogin');
Route::get('/registration', 'AuthController@registration');
Route::post('/post-registration', 'AuthController@postRegistration');
//Route::get('/dashboard', 'AuthController@dashboard');
//Route::get('logout', 'AuthController@logout');
Route::get('/logout', 'AuthController@logout')->name('logout')->middleware('auth');

/* hotel auth0 example

Route::view('/', 'home');
Route::get('/hotels', 'HotelController@index');
Route::get('/auth0/callback', '\Auth0\Login\Auth0Controller@callback' )->name('auth0-callback');
Route::get('/login', 'Auth\Auth0IndexController@login')->name('login');
Route::get('/logout', 'Auth\Auth0IndexController@logout')->name('logout')->middleware('auth');

Route::group(['prefix' => 'dashboard'], function() {
    Route::view('/', 'dashboard/dashboard');
    Route::get('reservations/create/{id}', 'ReservationController@create');
    Route::resource('reservations', 'ReservationController')->except('create');
});
*///

//Hotel Routes
Route::middleware('auth')->group(function () {
    Route::group(['prefix' => 'dashboard'], function () {
        Route::view('/', 'dashboard/dashboard');
        Route::get('reservations/create/{id}', 'ReservationController@create');
        Route::resource('reservations', 'ReservationController')->except('create');
    });
});

Route::post('jwtlogin', 'UserController@authenticate');

Route::view('/', 'home');
Route::get('/hotels', 'HotelController@index');
Route::get('/projects', 'ProjectController@index');

//add route to add tasks
//Route::group(['middleware' => 'auth.jwt'], function () {

  //  Route::post('task/{id}', 'TaskController@create');
   // Route::put('task/{id}', 'TaskController@update');

    Route::group(['prefix' => 'task'], function () {
       // Route::view('/', 'task');
        Route::get('logs/create/{id}', 'LogController@create');
        Route::resource('logs', 'LogController')->except('create');
    });
//});

resources/views/dashboard/dashboard.blade.php
<!-- resources/views/dashboard/dashboard.blade.php -->
@extends('index')
@section('title', 'Dashboard')
@section('content')
    <div class="container text-center my-5">
        <div class="row">
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Manage your Reservations</h4>
                        <p class="card-text">Modify your current reservations.</p>
                        <a href="/dashboard/reservations" class="btn btn-primary">My Reservations</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Find a Room</h4>
                        <p class="card-text">Browse our catalog of top-rated hotels.</p>
                        <a href="/hotels" class="btn btn-primary">Our Hotels</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/reservationCreate.blade.php
<!-- resources/views/dashboard/reservationCreate.blade.php -->
@extends('index')
@section('title', 'Create reservation')
@section('content')
    <div class="container my-5">
        <div class="card">
            <div class="card-header">
                <h2>{{ $hotelInfo->name }} - <small class="text-muted">{{ $hotelInfo->location }}</small></h2>
            </div>
            <div class="card-body">
                <h5 class="card-title"></h5>
                <p class="card-text">Book your stay now at the most magnificent resort in the world!</p>
                <form action="{{ route('reservations.store') }}" method="POST">
                    @csrf
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="form-group">
                                <label for="room">Room Type</label>
                                <select class="form-control" name="room_id">
                                    @foreach ($hotelInfo->rooms as $option)
                                        <option value="{{$option->id}}">{{ $option->type }} - ${{ $option->price }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="guests">Number of guests</label>
                                <input class="form-control" name="num_of_guests" placeholder="1">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="arrival">Arrival</label>
                                <input type="date" class="form-control" name="arrival" placeholder="03/21/2020">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="departure">Departure</label>
                                <input type="date" class="form-control" name="departure" placeholder="03/23/2020">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-lg btn-primary">Book it</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/reservationEdit.blade.php
<!-- resources/views/dashboard/reservationEdit.blade.php -->
@extends('index')
@section('title', 'Edit Reservation')
@section('content')
    <div class="container">
        <div class="card my-5">
            <div class="card-header">
                <h2>{{ $hotelInfo->name }} - <small class="text-muted">{{ $hotelInfo->location }}</small></h2>
            </div>
            <div class="card-body">
                <h5 class="card-title"></h5>
                <p class="card-text">Book your stay now at the most magnificent resort in the world!</p>
                <form action="{{ route('reservations.update', $reservation->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="form-group">
                                <label for="room">Room Type</label>
                                <select class="form-control" name="room_id" value="{{ old('room_id', $reservation->room_id) }}">
                                    @foreach ($hotelInfo->rooms as $option)
                                        <option value="{{$option->id}}">{{ $option->type }} - ${{ $option->price }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="guests">Number of guests</label>
                                <input class="form-control" name="num_of_guests" value="{{ old('num_of_guests', $reservation->num_of_guests) }}">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="arrival">Arrival</label>
                                <input type="date" class="form-control" name="arrival" placeholder="03/21/2020" value="{{ old('arrival', $reservation->arrival) }}">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="departure">Departure</label>
                                <input type="date" class="form-control" name="departure" placeholder="03/23/2020" value="{{ old('departure', $reservation->departure) }}">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-lg btn-primary">Submit</button>
                </form>
            </div>
        </div>
        <form action="{{ route('reservations.destroy', $reservation->id) }}" method="POST">
            @method('DELETE')
            @csrf
            <p class="text-right">
                <button type="submit" class="btn btn-sm text-danger">Delete reservation</button>
            </p>
        </form>
    </div>
@endsection

resources/views/dashboard/reservationSingle.blade.php
<!-- resources/views/dashboard/dashboard.blade.php -->
@extends('index')
@section('title', 'Edit Reservation')
@section('content')
    <div class="container">
        <div class="card my-5">
            <div class="card-header">
                <h2>You're all booked for the {{ $hotelInfo->name }} in {{ $hotelInfo->location }}!</h2>
            </div>
            <div class="card-body">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <img src="{{ $hotelInfo->image }}" class="img-fluid" alt="Front of hotel">
                        </div>
                        <div class="col-sm-6">
                            <h3 class="card-title">
                                {{ $hotelInfo->name }} - <small>{{ $hotelInfo->location }}</small>
                            </h3>
                            <p class="card-text">{{ $hotelInfo->description }}</p>
                            <p class="card-text"><strong>Arrival: </strong>{{ $reservation->arrival }}</p>
                            <p class="card-text"><strong>Departure: </strong>{{ $reservation->departure }}</p>
                            <p class="card-text"><strong>Room: </strong>{{ $reservation->room['type'] }}</p>
                            <p class="card-text"><strong>Guests: </strong>{{ $reservation->num_of_guests }}</p>
                            <p class="card-text"><strong>Price: </strong>${{ $reservation->room['price'] }}</p>
                        </div>
                    </div>
                    <div class="text-center mt-3">
                        <a href="/dashboard/reservations/{{ $reservation->id }}/edit" class="btn btn-lg btn-success">Edit this reservation</a>
                        <a href="/dashboard/reservations/{{ $reservation->id }}/delete" class="btn btn-lg btn-danger">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/reservations.blade.php
@extends('index')
@section('title', 'Reservations')
@section('content')
    <div class="container mt-5">
        <h2>Your Reservations</h2>
        <table class="table mt-3">
            <thead>
            <tr>
                <th scope="col">Hotel</th>
                <th scope="col">Arrival</th>
                <th scope="col">Departure</th>
                <th scope="col">Type</th>
                <th scope="col">Guests</th>
                <th scope="col">Price</th>
                <th scope="col">Manage</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($reservations as $reservation)
                <tr>
                    <td>{{ $reservation->room->hotel['name'] }}</td>
                    <td>{{ $reservation->arrival }}</td>
                    <td>{{ $reservation->departure }}</td>
                    <td>{{ $reservation->room['type'] }}</td>
                    <td>{{ $reservation->num_of_guests }}</td>
                    <td>${{ $reservation->room['price'] }}</td>
                    <td><a href="/dashboard/reservations/{{ $reservation->id }}/edit" class="btn btn-sm btn-success">Edit</a></td>
                </tr>
            @endforeach
            </tbody>
        </table>
        @if(!empty(Session::get('success')))
            <div class="alert alert-success"> {{ Session::get('success') }}</div>
        @endif
        @if(!empty(Session::get('error')))
            <div class="alert alert-danger"> {{ Session::get('error') }}</div>
        @endif
    </div>
@endsection