routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('login', 'AuthController@index');
Route::get('/login', 'AuthController@index')->name('login');

Route::post('/post-login', 'AuthController@postLogin');
Route::get('/registration', 'AuthController@registration');
Route::post('/post-registration', 'AuthController@postRegistration');
//Route::get('/dashboard', 'AuthController@dashboard');
//Route::get('logout', 'AuthController@logout');
Route::get('/logout', 'AuthController@logout')->name('logout')->middleware('auth');

/* hotel auth0 example

Route::view('/', 'home');
Route::get('/hotels', 'HotelController@index');
Route::get('/auth0/callback', '\Auth0\Login\Auth0Controller@callback' )->name('auth0-callback');
Route::get('/login', 'Auth\Auth0IndexController@login')->name('login');
Route::get('/logout', 'Auth\Auth0IndexController@logout')->name('logout')->middleware('auth');

Route::group(['prefix' => 'dashboard'], function() {
    Route::view('/', 'dashboard/dashboard');
    Route::get('reservations/create/{id}', 'ReservationController@create');
    Route::resource('reservations', 'ReservationController')->except('create');
});
*///

//Hotel Routes
Route::middleware('auth')->group(function () {
    Route::group(['prefix' => 'dashboard'], function () {
        Route::view('/', 'dashboard/dashboard');
        Route::get('reservations/create/{id}', 'ReservationController@create');
        Route::resource('reservations', 'ReservationController')->except('create');
    });
});

Route::post('jwtlogin', 'UserController@authenticate');

Route::view('/', 'home');
Route::get('/hotels', 'HotelController@index');
Route::get('/projects', 'ProjectController@index');

//add route to add tasks
//Route::group(['middleware' => 'auth.jwt'], function () {

  //  Route::post('task/{id}', 'TaskController@create');
   // Route::put('task/{id}', 'TaskController@update');

    Route::group(['prefix' => 'task'], function () {
       // Route::view('/', 'task');
        Route::get('logs/create/{id}', 'LogController@create');
        Route::resource('logs', 'LogController')->except('create');
    });
//});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    /**
     * @var string
     */
    protected $table = 'tasks';

    /**
     * @var array
     */
    protected $guarded = [];

    public function Project() {
        return $this->belongsTo('App\Project');
    }

    public function logs() {
        return $this->hasMany('App\Log');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use JWTAuth;
use App\Task;
use App\Project;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    /**
     * Display a listing of the tasks.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index() {
        $user_id = Auth::user()->id;
       /* $tasks = Task::with('project', 'project.department')
            ->where('user_id', $user_id)
            ->orderBy('created_at', 'asc')
            ->get();
       */
        $query = "SELECT tasks.* , p.title AS projectName FROM projects p JOIN tasks ON projects.id = tasks.project_id";
        $results = \DB::select($query);

        return view('task.tasks')->with('tasks', $results);
    }

    /**
     * Show the form for creating a new log.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create($project_id)
    {
       // $query = "SELECT tasks.* , p.title AS projectName FROM projects p JOIN tasks ON projects.id = tasks.project_id";
       // $results = \DB::select($query);

        $projectInfo = Project::with('tasks')->get()->find($project_id);
        return view('task.taskSelectForm', compact('projectInfo'));
    }

    /**
     * Store a newly created log in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $user_id = Auth::user()->id;
        $request->request->add(['user_id' => $user_id]);

        Log::create($request->all());

        return redirect('task/logs')->with('success', 'Log submitted!');
    }

    /**
     * Display the specified log.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function show(Log $log)
    {

        $user_id = Auth::user()->id;
        $log = Log::with('room', 'room.hotel')
            ->get()
            ->find($log->id);
        //user_id are not the same type at this design
        //  if ($log->user_id === $user_id) {
        if ($log->user_id == $user_id) {
            $project_id = $log->task->project_id;
            $projectInfo = Project::with('tasks')->get()->find($project_id);

            return view('task.taskSingle', compact('log', 'projectInfo'));
        }
        else
            return redirect('task/logs')->with('error', 'You are not authorized to see that.');
    }

    /**
     * Show the form for editing the specified log.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Log $log)
    {


        $user_id = Auth::user()->id;
        $log = Log::with('log', 'log.task')
            ->get()
            ->find($log->id);
        //user_id are not the same type at this design
        //  if ($log->user_id === $user_id) {
        if ($log->user_id == $user_id) {
            $project_id = $log->task->Project_id;
            $projectInfo = Project::with('tasks')->get()->find($project_id);

            return view('task.logEdit', compact('log', 'projectInfo'));
        } else
            return redirect('task/logs')->with('error', 'You are not authorized.');
    }

    /**
     * Update the specified log in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Log $log)
    {

        $user_id = Auth::user()->id;
        if ($log->user_id != $user_id){
            return redirect('task/logs')->with('error', 'You are not authorized to update this log');
        }else {
            //  $user_id = \Auth::user()->getUserInfo()['sub'];
            $log->user_id = $user_id;
            $log->num_of_persons = $request->num_of_persons;
            $log->start_date = $request->start_date;
            $log->end_date = $request->end_date;
            $log->title = $request->title;
            $log->description = $request->description;
            $log->save();

            return redirect('task/logs')->with('success', 'Successfully updated your log!!');
        }
    }

    /**
     * Remove the specified log from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Log $log)
    {

        $user_id = Auth::user()->id;
        $log = Reservation::find($log->id);
        //user_id are not the same type at this design
        //  if ($log->user_id === $user_id) {
        if ($log->user_id == $user_id) {
            $log->delete();

            return redirect('task/logs')->with('success', 'Successfully deleted your log!');
        } else
            return redirect('task/logs')->with('error', 'You are not authorized to delete this log');
    }
}

resources/views/task/addtaskform.blade.php
<!-- resources/views/dashboard/reservationCreate.blade.php -->
@extends('index')
@section('title', 'Create reservation')
@section('content')
    <div class="container my-5">
        <div class="card">
            <div class="card-header">
                <h2>{{ $projectInfo->name }} - <small class="text-muted">{{ $projectInfo->department }}</small></h2>
            </div>
            <div class="card-body">
                <h5 class="card-title"></h5>
                <p class="card-text">Create your task</p>
                <form action="{{ route('tasks.store') }}" method="POST">
                    @csrf
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="form-group">
                                <label for="room">Project</label>
                                <select class="form-control" name="room_id">
                                    @foreach ($projectInfo->names as $option)
                                        <option value="{{$option->id}}">{{ $option->name }} - ${{ $option->department }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="num_of _persons">Number of people</label>
                                <input class="form-control" name="num_of_persons" placeholder="1">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="startdate">Start Date</label>
                                <input type="date" class="form-control" name="startdate" placeholder="02/20/2020">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="enddate">End</label>
                                <input type="date" class="form-control" name="enddate" placeholder="12/20/2020">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-lg btn-primary">Create </button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/task/categories.blade.php
<?php
@extends('index')
@section('title', 'categories')
@section('content')
    <div class="container mt-5">
        <h2>Task categories</h2>
        <table class="table mt-3">
            <thead>
            <tr>
                <th scope="col">Category</th>
              <th scope="col">Department</th>
                <th scope="col">Department ID</th>
                <th scope="col">add/update</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($categories as $category)
                <tr>
                    <td>{{ $category->department->department['name'] }}</td>

                    <td>{{ $category->department['ID'] }}</td>

                    <td><a href="/tasks/{{ $category->id }}/edit" class="btn btn-sm btn-success">Edit</a></td>
                    <td><a href="/tasks/{{ $category->id }}/create" class="btn btn-sm btn-success">Create</a></td>
                </tr>
            @endforeach
            </tbody>
        </table>
        @if(!empty(Session::get('success')))
            <div class="alert alert-success"> {{ Session::get('success') }}</div>
        @endif
        @if(!empty(Session::get('error')))
            <div class="alert alert-danger"> {{ Session::get('error') }}</div>
        @endif
    </div>
@endsection
=======

resources/views/task/projects.blade.php
<?php

@extends('index')
@section('title', 'projects')
@section('content')
    <div class="container mt-5">
        <h2>Projects</h2>
        <table class="table mt-3">
            <thead>
            <tr>
                <th scope="col">Department</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Start date - End date</th>
                <th scope="col">add task</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($projects as $project)
                <tr>
                    <td>{{ $project->department->department['name'] }}</td>

                    <td>{{ $projet->title }}</td>
                    <td>{{ $projet->description }}</td>
                    <td>{{ $projet->startdate }} - {{ $projet->enddate }}</td>
                    <td>
                    <a href="/tasks/{{ $project->id }}/create" class="btn btn-sm btn-success">Add task to this project</a> |

                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        @if(!empty(Session::get('success')))
            <div class="alert alert-success"> {{ Session::get('success') }}</div>
        @endif
        @if(!empty(Session::get('error')))
            <div class="alert alert-danger"> {{ Session::get('error') }}</div>
        @endif
    </div>
@endsection

resources/views/task/taskCreate.blade.php
<!-- resources/views/dashboard/reservationCreate.blade.php -->
@extends('index')
@section('title', 'Create task')
@section('content')
    <div class="container my-5">
        <div class="card">
            <div class="card-header">
                <h2>{{ $projectInfo->title }} - <small class="text-muted">{{ $projectInfo->startdate }}</small></h2>
            </div>
            <div class="card-body">
                <h5 class="card-title"></h5>
                <p class="card-text">Create your task</p>
                <form action="{{ route('tasks.store') }}" method="POST">
                    @csrf
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="form-group">
                                <label for="room">Select project department</label>
                                <select class="form-control" name="room_id">
                                    @foreach ($projectInfo->names as $option)
                                        <option value="{{$option->id}}">{{ $option->name }} - ${{ $option->location }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="num_of _persons">Number of people</label>
                                <input class="form-control" name="num_of_persons" placeholder="1">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="startdate">Start Date</label>
                                <input type="date" class="form-control" name="startdate" placeholder="02/20/2020">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="enddate">End</label>
                                <input type="date" class="form-control" name="enddate" placeholder="12/20/2020">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-lg btn-primary">Create </button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/task/taskSelectForm.blade.php
<!-- resources/views/dashboard/reservationCreate.blade.php -->
@extends('index')
@section('title', 'Create task')
@section('content')
    <div class="container my-5">
        <div class="card">
            <div class="card-header">
                <h2>{{ $projectInfo->title }} - <small class="text-muted">{{ $projectInfo->startdate }}</small></h2>
            </div>
            <div class="card-body">
                <h5 class="card-title"></h5>
                <p class="card-text">Create your task</p>
                <form action="{{ route('logs.store') }}" method="POST">
                    @csrf
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="form-group">
                                <label for="room">Select project department</label>
                                <select class="form-control" name="task_id">
                                    @foreach ($projectInfo->names as $option)
                                        <option value="{{$option->id}}">{{ $option->name }} - ${{ $option->location }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="num_of _persons">Number of people</label>
                                <input class="form-control" name="num_of_persons" placeholder="1">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="start_date">Start Date</label>
                                <input type="date" class="form-control" name="startdate" placeholder="2020-02-26">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="end_date">End</label>
                                <input type="date" class="form-control" name="enddate" placeholder="2029-02-26">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-lg btn-primary">Submit Log</button>
                </form>
            </div>
        </div>
    </div>
@endsection